#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/camellia/modular_camellia.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_camellia.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 yasutoshi-lab and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from huggingface_hub.dataclasses import strict

from ...configuration_utils import PreTrainedConfig
from ...utils import auto_docstring


@auto_docstring(checkpoint="yasutoshi-lab/camellia-3b")
@strict
class CamelliaConfig(PreTrainedConfig):
    r"""
    Configuration for Camellia: DeepSeek-V3 style MoE with a KDA:MLA 3:1
    hybrid attention layout (NoPE MLA), one MTP head (D=1).

    KDA / hybrid fields:
    - `linear_attn_ratio`: number of consecutive KDA layers before each MLA
      layer. 3 gives the [KDA, KDA, KDA, MLA] x 7 layout for 28 layers.
    - `kda_num_heads` / `kda_head_dim` / `short_conv_kernel_size`: KDA layer
      geometry (projection size = kda_num_heads * kda_head_dim).

    MTP fields:
    - `num_nextn_predict_layers`: MTP depth (1 = predict one extra token).
    - `mtp_lambda_high` / `mtp_lambda_low` / `mtp_lambda_switch_frac`: MTP loss
      weight schedule. The weight is `mtp_lambda_high` until
      `mtp_lambda_switch_frac * total_steps`, then `mtp_lambda_low` (V3 style:
      the switch lands in the final ~30% of training, not at the midpoint).

    Packed training:
    - `eos_token_id` doubles as the intra-document boundary marker used to
      build `cu_seqlens` for the KDA / varlen-MLA paths.

    Args:
        n_group (`int`, defaults to `8`): Number of expert groups for
            group-limited routing (V3). Each group holds
            `n_routed_experts // n_group` experts.
        topk_group (`int`, defaults to `4`): Number of groups considered for
            routing (V3).
        first_k_dense_replace (`int`, defaults to `1`): Number of initial
            layers using a dense FFN instead of MoE (V3).
        rope_interleave (`bool`, defaults to `True`): Whether the rotary
            position embedding uses interleaved weights. Unused under NoPE;
            kept for config compatibility.
        linear_attn_ratio (`int`, defaults to `3`): Number of consecutive KDA
            layers before each MLA layer. 3 gives the
            [KDA, KDA, KDA, MLA] x 7 layout for 28 layers.
        kda_num_heads (`int`, defaults to `12`): KDA attention heads
            (projection size = kda_num_heads * kda_head_dim).
        kda_head_dim (`int`, defaults to `128`): KDA per-head dimension.
        short_conv_kernel_size (`int`, defaults to `4`): KDA short
            convolution kernel size.
        num_nextn_predict_layers (`int`, defaults to `1`): MTP depth
            (1 = predict one extra token).
        mtp_lambda_high (`float`, defaults to `0.3`): MTP loss weight until
            the switch step.
        mtp_lambda_low (`float`, defaults to `0.1`): MTP loss weight after
            the switch step.
        mtp_lambda_switch_frac (`float`, defaults to `0.7`): Fraction of
            total steps at which the MTP loss weight switches (V3 style:
            the switch lands in the final ~30% of training, not at the
            midpoint).
    """

    model_type = "camellia"
    keys_to_ignore_at_inference = ["past_key_values"]
    base_model_tp_plan = {
        "layers.*.mlp.experts.gate_up_proj": "packed_colwise",
        "layers.*.mlp.experts.down_proj": "rowwise",
        "layers.*.mlp.experts": "moe_tp_experts",
        "layers.*.mlp.shared_experts.gate_proj": "colwise",
        "layers.*.mlp.shared_experts.up_proj": "colwise",
        "layers.*.mlp.shared_experts.down_proj": "rowwise",
        "layers.*.mlp.gate_proj": "colwise",
        "layers.*.mlp.up_proj": "colwise",
        "layers.*.mlp.down_proj": "rowwise",
    }
    base_model_pp_plan = {
        "embed_tokens": (["input_ids"], ["inputs_embeds"]),
        "layers": (["hidden_states", "attention_mask"], ["hidden_states"]),
        "norm": (["hidden_states"], ["hidden_states"]),
    }
    attribute_map = {
        "num_local_experts": "n_routed_experts",
    }

    # --- Camellia-3B defaults (design report §1) ---
    vocab_size: int = 128_000
    hidden_size: int = 1_536
    intermediate_size: int = 4_224
    moe_intermediate_size: int = 320
    num_hidden_layers: int = 28
    num_attention_heads: int = 16
    num_key_value_heads: int | None = 128
    n_shared_experts: int = 1
    n_routed_experts: int = 64
    routed_scaling_factor: float = 2.5
    kv_lora_rank: int = 384
    q_lora_rank: int | None = None
    qk_rope_head_dim: int = 0  # NoPE
    v_head_dim: int | None = 96
    qk_nope_head_dim: int = 96
    n_group: int | None = 8
    topk_group: int | None = 4
    num_experts_per_tok: int | None = 6
    first_k_dense_replace: int | None = 1
    norm_topk_prob: bool | None = True
    hidden_act: str = "silu"
    max_position_embeddings: int = 8_192
    initializer_range: float = 0.02
    rms_norm_eps: float = 1e-6
    use_cache: bool = True
    pad_token_id: int | None = None
    bos_token_id: int | None = 0
    eos_token_id: int | list[int] | None = 1
    pretraining_tp: int | None = 1
    tie_word_embeddings: bool = True
    rope_parameters: object = None
    rope_interleave: bool | None = True
    attention_bias: bool = False
    attention_dropout: float | int | None = 0.0

    # --- KDA hybrid (design §1) ---
    linear_attn_ratio: int = 3
    kda_num_heads: int = 12
    kda_head_dim: int = 128
    short_conv_kernel_size: int = 4

    # --- MTP (design §1) ---
    num_nextn_predict_layers: int = 1
    mtp_lambda_high: float = 0.3
    mtp_lambda_low: float = 0.1
    mtp_lambda_switch_frac: float = 0.7

    def __post_init__(self, **kwargs):
        # NoPE: rotary embedding is constructed (base __init__) but never called;
        # give it a valid rope_parameters dict to keep construction happy.
        if self.rope_parameters is None:
            self.rope_parameters = {"rope_type": "default", "rope_theta": 10_000.0}
        if self.num_key_value_heads is None:
            self.num_key_value_heads = self.num_attention_heads

        self.qk_head_dim = self.qk_nope_head_dim + self.qk_rope_head_dim
        self.head_dim = self.qk_rope_head_dim
        super().__post_init__(**kwargs)


__all__ = ["CamelliaConfig"]
