#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/camellia/modular_camellia.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_camellia.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 yasutoshi-lab and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
from collections.abc import Callable
from typing import Optional

import torch
import torch.nn.functional as F
from torch import nn

from ... import initialization as init
from ...activations import ACT2FN
from ...cache_utils import Cache
from ...generation import GenerationMixin
from ...integrations import use_experts_implementation, use_kernel_forward_from_hub, use_kernel_func_from_hub
from ...modeling_flash_attention_utils import FlashAttentionKwargs
from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast
from ...modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from ...processing_utils import Unpack
from ...utils import TransformersKwargs, auto_docstring, can_return_tuple
from ...utils.generic import is_flash_attention_requested, maybe_autocast
from .configuration_camellia import CamelliaConfig

# Post-generation patch (stable): third-party kernels (fla-core KDA, flash-attn varlen)
try:
    from fla.modules import FusedRMSNormGated, ShortConvolution
    from fla.ops.kda import chunk_kda, fused_recurrent_kda
    from fla.ops.kda.gate import fused_kda_gate
except ImportError:
    raise ImportError("Please run `pip install -U fla-core`")

try:
    from flash_attn import flash_attn_varlen_func
except ImportError:
    flash_attn_varlen_func = None

# Post-generation patch (stable): the converter keeps these base-model
# references in inlined / modular code; import them explicitly.
from ..deepseek_v3.modeling_deepseek_v3 import (
    DeepseekV3MLP,
    DeepseekV3NaiveMoe,
    DeepseekV3RMSNorm,
)


class CamelliaKDAAttention(nn.Module):
    """Kimi Delta Attention layer (fla-core KDA), Kimi-Linear parameter layout.

    Training path only (chunk kernel). With `cu_seqlens` the layer operates on
    the flattened packed stream ([1, B*T, ...] convention required by both
    `ShortConvolution` and `chunk_kda`) and resets the recurrent state at every
    intra-document boundary.
    """

    def __init__(self, config: CamelliaConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.hidden_size = config.hidden_size
        self.num_heads = config.kda_num_heads
        self.head_dim = config.kda_head_dim
        self.conv_size = config.short_conv_kernel_size
        projection = self.num_heads * self.head_dim

        self.q_proj = nn.Linear(self.hidden_size, projection, bias=False)
        self.k_proj = nn.Linear(self.hidden_size, projection, bias=False)
        self.v_proj = nn.Linear(self.hidden_size, projection, bias=False)
        self.q_conv1d = ShortConvolution(projection, kernel_size=self.conv_size, activation="silu")
        self.k_conv1d = ShortConvolution(projection, kernel_size=self.conv_size, activation="silu")
        self.v_conv1d = ShortConvolution(projection, kernel_size=self.conv_size, activation="silu")
        # A_log / dt_bias stay fp32 (kernel contract, verified on sm_120)
        self.A_log = nn.Parameter(torch.log(torch.empty(self.num_heads, dtype=torch.float32).uniform_(1, 16)))
        self.f_a_proj = nn.Linear(self.hidden_size, self.head_dim, bias=False)
        self.f_b_proj = nn.Linear(self.head_dim, projection, bias=False)
        self.dt_bias = nn.Parameter(torch.empty(projection, dtype=torch.float32))
        self.b_proj = nn.Linear(self.hidden_size, self.num_heads, bias=False)
        self.g_a_proj = nn.Linear(self.hidden_size, self.head_dim, bias=False)
        self.g_b_proj = nn.Linear(self.head_dim, projection, bias=False)
        self.o_norm = FusedRMSNormGated(self.head_dim, eps=config.rms_norm_eps, activation="sigmoid")
        self.o_proj = nn.Linear(projection, self.hidden_size, bias=False)
        self.o_proj._is_residual_proj = True

    def forward(
        self,
        hidden_states: torch.Tensor,
        cu_seqlens: torch.Tensor | None = None,
        **kwargs,
    ) -> tuple[torch.Tensor, None]:
        B, T, _ = hidden_states.shape
        if cu_seqlens is not None:
            h = hidden_states.reshape(1, B * T, -1)  # packed convention: B must be 1
        else:
            h = hidden_states
        q = self.q_conv1d(self.q_proj(h), cu_seqlens=cu_seqlens)[0]
        k = self.k_conv1d(self.k_proj(h), cu_seqlens=cu_seqlens)[0]
        v = self.v_conv1d(self.v_proj(h), cu_seqlens=cu_seqlens)[0]
        # 0.5.2 API: g must be [..., H, K] before the fused gate kernel
        g = self.f_b_proj(self.f_a_proj(h)).view(*h.shape[:-1], self.num_heads, self.head_dim)
        g = fused_kda_gate(g, self.A_log, self.dt_bias)
        beta = self.b_proj(h).float().sigmoid()
        if cu_seqlens is not None:
            q = q.view(1, B * T, self.num_heads, self.head_dim)
            k = k.view(1, B * T, self.num_heads, self.head_dim)
            v = v.view(1, B * T, self.num_heads, self.head_dim)
            g = g.view(1, B * T, self.num_heads, self.head_dim)
            beta = beta.view(1, B * T, self.num_heads)
            mode = "chunk" if B * T > 64 else "fused_recurrent"
        else:
            q = q.view(B, T, self.num_heads, self.head_dim)
            k = k.view(B, T, self.num_heads, self.head_dim)
            v = v.view(B, T, self.num_heads, self.head_dim)
            g = g.view(B, T, self.num_heads, self.head_dim)
            beta = beta.view(B, T, self.num_heads)
            mode = "chunk" if T > 64 else "fused_recurrent"
        kernel = chunk_kda if mode == "chunk" else fused_recurrent_kda
        o, _ = kernel(
            q=q,
            k=k,
            v=v,
            g=g,
            beta=beta,
            use_qk_l2norm_in_kernel=True,
            cu_seqlens=cu_seqlens,
        )
        o = o.view(B, T, self.num_heads, self.head_dim)
        gate = self.g_b_proj(self.g_a_proj(hidden_states)).view(B, T, self.num_heads, self.head_dim)
        o = self.o_norm(o, gate)
        o = self.o_proj(o.reshape(B, T, self.num_heads * self.head_dim))
        return o, None


class CamelliaMLAAttention(nn.Module):
    """DeepSeek MLA with NoPE + per-head QK-Norm + varlen (cu_seqlens) support.

    Training path: low-rank KV (kv_lora_rank) is expanded to per-head k/v and
    attention runs through `flash_attn_varlen_func` when `cu_seqlens` is given
    (intra-document boundaries), otherwise through SDPA with a causal mask.
    """

    def __init__(self, config: CamelliaConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.num_heads = config.num_attention_heads
        self.qk_nope_head_dim = config.qk_nope_head_dim
        self.v_head_dim = config.v_head_dim
        self.kv_lora_rank = config.kv_lora_rank
        self.scaling = self.qk_nope_head_dim**-0.5

        self.q_proj = nn.Linear(config.hidden_size, self.num_heads * self.qk_nope_head_dim, bias=False)
        # QK-Norm (Qwen3 / nanochat style, per head)
        self.q_norm = DeepseekV3RMSNorm(self.qk_nope_head_dim, eps=config.rms_norm_eps)
        self.k_norm = DeepseekV3RMSNorm(self.qk_nope_head_dim, eps=config.rms_norm_eps)
        self.kv_a_proj = nn.Linear(config.hidden_size, self.kv_lora_rank, bias=False)
        self.kv_a_layernorm = DeepseekV3RMSNorm(self.kv_lora_rank, eps=config.rms_norm_eps)
        self.kv_b_proj = nn.Linear(
            self.kv_lora_rank, self.num_heads * (self.qk_nope_head_dim + self.v_head_dim), bias=False
        )
        self.o_proj = nn.Linear(self.num_heads * self.v_head_dim, config.hidden_size, bias=False)
        self.o_proj._is_residual_proj = True

    def forward(
        self,
        hidden_states: torch.Tensor,
        cu_seqlens: torch.Tensor | None = None,
        **kwargs,
    ) -> tuple[torch.Tensor, None]:
        B, T, _ = hidden_states.shape
        q = self.q_proj(hidden_states).view(B, T, self.num_heads, self.qk_nope_head_dim)
        q = self.q_norm(q)
        kv = self.kv_a_layernorm(self.kv_a_proj(hidden_states))
        kv = self.kv_b_proj(kv).view(B, T, self.num_heads, self.qk_nope_head_dim + self.v_head_dim)
        k = kv[..., : self.qk_nope_head_dim]
        v = kv[..., self.qk_nope_head_dim :]
        k = self.k_norm(k)

        if cu_seqlens is not None:
            S = B * T
            if flash_attn_varlen_func is not None:
                max_len = int((cu_seqlens[1:] - cu_seqlens[:-1]).max().item())
                qf = q.reshape(S, self.num_heads, self.qk_nope_head_dim)
                kf = k.reshape(S, self.num_heads, self.qk_nope_head_dim)
                vf = v.reshape(S, self.num_heads, self.v_head_dim)
                o = flash_attn_varlen_func(
                    qf,
                    kf,
                    vf,
                    cu_seqlens_q=cu_seqlens.to(torch.int32),
                    cu_seqlens_k=cu_seqlens.to(torch.int32),
                    max_seqlen_q=max_len,
                    max_seqlen_k=max_len,
                    softmax_scale=self.scaling,
                    causal=True,
                )
                o = o.view(B, T, self.num_heads, self.v_head_dim)
            else:  # SDPA fallback: per-document causal attention.
                # Documents are contiguous segments of the flattened stream,
                # so a block-diagonal mask is equivalent to causal attention
                # per segment. (A 2-D bool [S, S] mask is mishandled by SDPA
                # on torch 2.11 / sm_120 — verified 2026-09-26.)
                qf = q.reshape(S, self.num_heads, self.qk_nope_head_dim)
                kf = k.reshape(S, self.num_heads, self.qk_nope_head_dim)
                vf = v.reshape(S, self.num_heads, self.v_head_dim)
                out_parts = []
                start = 0
                for length in (cu_seqlens[1:] - cu_seqlens[:-1]).tolist():
                    end = start + length
                    out_parts.append(
                        F.scaled_dot_product_attention(
                            qf[start:end].transpose(0, 1),
                            kf[start:end].transpose(0, 1),
                            vf[start:end].transpose(0, 1),
                            is_causal=True,
                            scale=self.scaling,
                        ).transpose(0, 1)
                    )
                    start = end
                o = torch.cat(out_parts, dim=0).view(B, T, self.num_heads, self.v_head_dim)
        else:
            qh = q.transpose(1, 2)
            kh = k.transpose(1, 2)
            vh = v.transpose(1, 2)
            o = F.scaled_dot_product_attention(qh, kh, vh, is_causal=True, scale=self.scaling)
            o = o.transpose(1, 2)

        o = self.o_proj(o.reshape(B, T, self.num_heads * self.v_head_dim))
        return o, None


@use_experts_implementation
class CamelliaNaiveMoe(nn.Module):
    """Expert collection with per-expert output RMS statistics (design §6).

    The parent model attaches an `[E]` fp32 counter (`_out_norm_stats`) and a
    hit counter (`_out_hit_stats`); the forward loop accumulates the RMS of
    each expert's contribution (before the top-k weighting) for the outlier-
    expert / Localized Activation Blow-up monitoring.
    """

    _out_norm_stats: torch.Tensor | None
    _out_hit_stats: torch.Tensor | None

    def __init__(self, config):
        super().__init__()
        self.num_experts = config.num_local_experts
        self.hidden_dim = config.hidden_size
        self.intermediate_dim = config.moe_intermediate_size
        self.gate_up_proj = nn.Parameter(torch.empty(self.num_experts, 2 * self.intermediate_dim, self.hidden_dim))
        self.down_proj = nn.Parameter(torch.empty(self.num_experts, self.hidden_dim, self.intermediate_dim))
        self.act_fn = ACT2FN[config.hidden_act]
        self._out_norm_stats = None
        self._out_hit_stats = None

    def forward(self, hidden_states, top_k_index, top_k_weights) -> torch.Tensor:
        final_hidden_states = torch.zeros_like(hidden_states)
        with torch.no_grad():
            expert_mask = torch.nn.functional.one_hot(top_k_index, num_classes=self.num_experts)
            expert_mask = expert_mask.permute(2, 1, 0)
            expert_hit = torch.greater(expert_mask.sum(dim=(-1, -2)), 0).nonzero()

        for expert_idx in expert_hit:
            expert_idx = expert_idx[0]
            if expert_idx == self.num_experts:
                continue
            top_k_pos, token_idx = torch.where(expert_mask[expert_idx])
            current_state = hidden_states[token_idx]
            gate, up = nn.functional.linear(current_state, self.gate_up_proj[expert_idx]).chunk(2, dim=-1)
            current_hidden_states = self.act_fn(gate) * up
            current_hidden_states = nn.functional.linear(current_hidden_states, self.down_proj[expert_idx])
            if self._out_norm_stats is not None:
                with torch.no_grad():
                    rms = current_hidden_states.float().pow(2).mean(dim=-1).sqrt().mean().clamp_max(1e6)
                    self._out_norm_stats[expert_idx].add_(rms)
                    self._out_hit_stats[expert_idx].add_(1)
            current_hidden_states = current_hidden_states * top_k_weights[token_idx, top_k_pos, None]
            final_hidden_states.index_add_(0, token_idx, current_hidden_states.to(final_hidden_states.dtype))

        return final_hidden_states


class CamelliaMLP(nn.Module):
    def __init__(self, config, intermediate_size=None):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size if intermediate_size is None else intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]
        # Post-generation patch (stable): shared-expert down_proj is a
        # residual-stream projection (design §7 item 3).
        self.down_proj._is_residual_proj = True

    def forward(self, x):
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


class CamelliaTopkRouter(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.n_routed_experts = config.n_routed_experts

        self.weight = nn.Parameter(torch.empty((self.n_routed_experts, config.hidden_size)))
        self.register_buffer("e_score_correction_bias", torch.zeros(self.n_routed_experts))

    def forward(self, hidden_states):
        hidden_states = hidden_states.view(-1, self.config.hidden_size)
        router_logits = F.linear(hidden_states.type(torch.float32), self.weight.type(torch.float32))
        return router_logits


class CamelliaMoE(nn.Module):
    """DeepSeek-V3 MoE block with per-layer routed-expert load statistics.

    The parent model attaches shared fp32 counters to each MoE block:
    `_load_stats` `[E]` (routed token counts per expert) and, on the expert
    collection, `_out_norm_stats` / `_out_hit_stats` `[E]` (per-expert output
    RMS, see `CamelliaNaiveMoe`). Training-side callbacks all-reduce the
    counters for the global whole-batch load distribution (design §7
    実装前確定事項 2 / §6 MaxVio・expert 出力ノルム).
    """

    _load_stats: torch.Tensor | None

    def __init__(self, config: CamelliaConfig):
        super().__init__()
        self.config = config
        self.experts = CamelliaNaiveMoe(config)
        self.gate = CamelliaTopkRouter(config)
        self.shared_experts = CamelliaMLP(
            config=config, intermediate_size=config.moe_intermediate_size * config.n_shared_experts
        )
        self.n_routed_experts = config.n_routed_experts
        self.n_group = config.n_group
        self.topk_group = config.topk_group
        self.norm_topk_prob = config.norm_topk_prob
        self.routed_scaling_factor = config.routed_scaling_factor
        self.top_k = config.num_experts_per_tok
        self._load_stats = None

    def route_tokens_to_experts(self, router_logits):
        router_logits = router_logits.sigmoid()
        router_logits_for_choice = router_logits + self.gate.e_score_correction_bias
        group_scores = (
            router_logits_for_choice.view(-1, self.n_group, self.n_routed_experts // self.n_group)
            .topk(2, dim=-1)[0]
            .sum(dim=-1)
        )
        group_idx = torch.topk(group_scores, k=self.topk_group, dim=-1, sorted=False)[1]
        group_mask = torch.zeros_like(group_scores)
        group_mask.scatter_(1, group_idx, 1)
        score_mask = (
            group_mask.unsqueeze(-1)
            .expand(-1, self.n_group, self.n_routed_experts // self.n_group)
            .reshape(-1, self.n_routed_experts)
        )
        scores_for_choice = router_logits_for_choice.masked_fill(~score_mask.bool(), 0.0)
        topk_indices = torch.topk(scores_for_choice, k=self.top_k, dim=-1, sorted=False)[1]
        topk_weights = router_logits.gather(1, topk_indices)
        if self.norm_topk_prob:
            denominator = topk_weights.sum(dim=-1, keepdim=True) + 1e-20
            topk_weights /= denominator
        topk_weights = topk_weights * self.routed_scaling_factor
        return topk_indices, topk_weights

    def forward(self, hidden_states: torch.Tensor):
        residuals = hidden_states
        orig_shape = hidden_states.shape
        router_logits = self.gate(hidden_states)
        topk_indices, topk_weights = self.route_tokens_to_experts(router_logits)
        hidden_states = hidden_states.view(-1, hidden_states.shape[-1])
        hidden_states = self.experts(hidden_states, topk_indices, topk_weights).view(*orig_shape)
        hidden_states = hidden_states + self.shared_experts(residuals)
        if self._load_stats is not None:
            with torch.no_grad():
                counts = topk_indices.view(-1).bincount(minlength=self.n_routed_experts)
                self._load_stats.add_(counts.to(self._load_stats.dtype).to(self._load_stats.device))
        return hidden_states


@use_kernel_forward_from_hub("RMSNorm")
class CamelliaRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps: float = 1e-6) -> None:
        """
        CamelliaRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


@use_kernel_func_from_hub("rotary_pos_emb")
def apply_rotary_pos_emb(q, k, cos, sin, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        attn_weights = attn_weights + attention_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


def apply_rotary_pos_emb_interleave(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    r"""
    TODO let's just use the original freqcis computation to not have the view
    transpose + reshape! This is not optimized!
    Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        position_ids (`torch.Tensor`):
            The position indices of the tokens corresponding to the query and key tensors. For example, this can be
            used to pass offsetted position ids when working with a KV-cache.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)

    b, h, s, d = q.shape
    q = q.view(b, h, s, d // 2, 2).transpose(4, 3).reshape(b, h, s, d)

    b, h, s, d = k.shape
    k = k.view(b, h, s, d // 2, 2).transpose(4, 3).reshape(b, h, s, d)

    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def yarn_get_mscale(scale=1, mscale=1):
    if scale <= 1:
        return 1.0
    return 0.1 * mscale * math.log(scale) + 1.0


class CamelliaAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: CamelliaConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.attention_dropout = config.attention_dropout
        self.num_heads = config.num_attention_heads

        self.q_lora_rank = config.q_lora_rank
        self.qk_rope_head_dim = config.qk_rope_head_dim
        self.kv_lora_rank = config.kv_lora_rank
        self.v_head_dim = config.v_head_dim
        self.qk_nope_head_dim = config.qk_nope_head_dim
        self.qk_head_dim = config.qk_head_dim

        self.is_causal = True
        if self.q_lora_rank is None:
            self.q_proj = nn.Linear(config.hidden_size, self.num_heads * self.qk_head_dim, bias=False)
        else:
            self.q_a_proj = nn.Linear(config.hidden_size, config.q_lora_rank, bias=config.attention_bias)
            self.q_a_layernorm = CamelliaRMSNorm(config.q_lora_rank)
            self.q_b_proj = nn.Linear(config.q_lora_rank, self.num_heads * self.qk_head_dim, bias=False)

        self.kv_a_proj_with_mqa = nn.Linear(
            config.hidden_size,
            self.kv_lora_rank + self.qk_rope_head_dim,
            bias=config.attention_bias,
        )
        self.kv_a_layernorm = CamelliaRMSNorm(self.kv_lora_rank)
        self.kv_b_proj = nn.Linear(
            self.kv_lora_rank,
            self.num_heads * (self.qk_nope_head_dim + self.v_head_dim),
            bias=False,
        )

        self.o_proj = nn.Linear(
            self.num_heads * self.v_head_dim,
            config.hidden_size,
            bias=config.attention_bias,
        )

        self.scaling = self.qk_head_dim ** (-0.5)
        if self.config.rope_parameters.get("rope_type", "default") != "default":
            mscale_all_dim = self.config.rope_parameters.get("mscale_all_dim", 0)
            scaling_factor = self.config.rope_parameters["factor"]
            if mscale_all_dim:
                mscale = yarn_get_mscale(scaling_factor, mscale_all_dim)
                self.scaling = self.scaling * mscale * mscale

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: torch.Tensor | None,
        past_key_values: Cache | None = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.Tensor, torch.Tensor | None, tuple[torch.Tensor] | None]:
        batch_size, seq_length = hidden_states.shape[:-1]
        query_shape = (batch_size, seq_length, -1, self.qk_head_dim)
        key_shape = (batch_size, seq_length, -1, self.qk_nope_head_dim + self.v_head_dim)

        if self.q_lora_rank is None:
            q_states = self.q_proj(hidden_states)
        else:
            q_states = self.q_b_proj(self.q_a_layernorm(self.q_a_proj(hidden_states)))
        q_states = q_states.view(query_shape).transpose(1, 2)
        q_pass, q_rot = torch.split(q_states, [self.qk_nope_head_dim, self.qk_rope_head_dim], dim=-1)

        compressed_kv = self.kv_a_proj_with_mqa(hidden_states)
        k_pass, k_rot = torch.split(compressed_kv, [self.kv_lora_rank, self.qk_rope_head_dim], dim=-1)

        k_pass = self.kv_b_proj(self.kv_a_layernorm(k_pass)).view(key_shape).transpose(1, 2)
        k_pass, value_states = torch.split(k_pass, [self.qk_nope_head_dim, self.v_head_dim], dim=-1)

        k_rot = k_rot.view(batch_size, 1, seq_length, self.qk_rope_head_dim)

        cos, sin = position_embeddings
        if self.config.rope_interleave:  # support using interleaved weights for efficiency
            q_rot, k_rot = apply_rotary_pos_emb_interleave(q_rot, k_rot, cos, sin)
        else:
            q_rot, k_rot = apply_rotary_pos_emb(q_rot, k_rot, cos, sin)
        k_rot = k_rot.expand(*k_pass.shape[:-1], -1)

        query_states = torch.cat((q_pass, q_rot), dim=-1)
        key_states = torch.cat((k_pass, k_rot), dim=-1)

        if past_key_values is not None:
            key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx)

        if is_flash_attention_requested(self.config) and self.qk_head_dim != self.v_head_dim:
            value_states = F.pad(value_states, [0, self.qk_head_dim - self.v_head_dim])

        attention_interface: Callable = ALL_ATTENTION_FUNCTIONS.get_interface(
            self.config._attn_implementation, eager_attention_forward
        )

        attn_output, attn_weights = attention_interface(
            self,
            query_states,
            key_states,
            value_states,
            attention_mask,
            dropout=0.0 if not self.training else self.attention_dropout,
            scaling=self.scaling,
            **kwargs,
        )

        if is_flash_attention_requested(self.config) and self.qk_head_dim != self.v_head_dim:
            attn_output = attn_output[:, :, :, : self.v_head_dim]

        attn_output = attn_output.reshape(batch_size, seq_length, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights


class CamelliaDecoderLayer(GradientCheckpointingLayer):
    """Pre-norm decoder layer. Attention type is fixed by layer index:
    `layer_idx % (linear_attn_ratio + 1) == linear_attn_ratio` -> MLA, else KDA.
    FFN is dense for `layer_idx < first_k_dense_replace`, MoE otherwise.
    """

    def __init__(self, config: CamelliaConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = CamelliaAttention(config=config, layer_idx=layer_idx)

        if layer_idx >= config.first_k_dense_replace:
            self.mlp = CamelliaMoE(config)
        else:
            self.mlp = CamelliaMLP(config)
        self.input_layernorm = DeepseekV3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = DeepseekV3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.is_mla = layer_idx % (config.linear_attn_ratio + 1) == config.linear_attn_ratio
        if self.is_mla:
            self.self_attn = CamelliaMLAAttention(config, layer_idx)
        else:
            self.self_attn = CamelliaKDAAttention(config, layer_idx)
        if layer_idx >= config.first_k_dense_replace:
            self.mlp = CamelliaMoE(config)
        else:
            self.mlp = DeepseekV3MLP(config)
            self.mlp.down_proj._is_residual_proj = True

    def forward(
        self,
        hidden_states: torch.Tensor,
        cu_seqlens: torch.Tensor | None = None,
        **kwargs,
    ) -> torch.Tensor:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)
        hidden_states, _ = self.self_attn(hidden_states, cu_seqlens=cu_seqlens, **kwargs)
        hidden_states = residual + hidden_states

        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states
        return hidden_states


class CamelliaMTPModule(nn.Module):
    """One-step Multi-Token-Prediction module (V3 style, D=1).

    Input: `[B, T, 2D]` = concat(embed(x_{t+1}), hidden_t) for t = 0..T-2.
    One full block: fc(2D->D) + RMSNorm + MLA (NoPE) + RMSNorm + dense FFN.
    The model's final norm and lm_head are shared with the main path.
    """

    def __init__(self, config: CamelliaConfig):
        super().__init__()
        self.fc = nn.Linear(2 * config.hidden_size, config.hidden_size, bias=False)
        self.input_layernorm = DeepseekV3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.self_attn = CamelliaMLAAttention(config, layer_idx=config.num_hidden_layers)
        self.post_attention_layernorm = DeepseekV3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.mlp = DeepseekV3MLP(config)
        self.mlp.down_proj._is_residual_proj = True

    def forward(self, combined: torch.Tensor, cu_seqlens: torch.Tensor | None = None) -> torch.Tensor:
        hidden_states = self.fc(combined)
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)
        hidden_states, _ = self.self_attn(hidden_states, cu_seqlens=cu_seqlens)
        hidden_states = residual + hidden_states
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states
        return hidden_states


@auto_docstring
class CamelliaPreTrainedModel(PreTrainedModel):
    config: CamelliaConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["CamelliaDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn = True
    _supports_sdpa = True
    _supports_flex_attn = False
    _can_compile_fullgraph = False
    _supports_attention_backend = False
    _can_record_outputs = {
        "hidden_states": CamelliaDecoderLayer,
        "attentions": CamelliaAttention,
    }
    _keep_in_fp32_modules_strict = ["e_score_correction_bias", "A_log", "dt_bias"]
    _keys_to_ignore_on_load_unexpected = [r"model\.layers\.61.*"]
    _tp_plan: dict = {}
    _pp_plan: dict = {}

    @torch.no_grad()
    def _init_weights(self, module):
        super()._init_weights(module)
        if isinstance(module, CamelliaTopkRouter):
            init.normal_(module.weight, mean=0.0, std=self.config.initializer_range)
            init.zeros_(module.e_score_correction_bias)
        elif isinstance(module, CamelliaNaiveMoe):
            init.normal_(module.gate_up_proj, mean=0.0, std=self.config.initializer_range)
            # Post-generation patch (stable): the converter flattens the modular's
            # `CamelliaNaiveMoe(DeepseekV3NaiveMoe)` inheritance, so the scaled-init
            # `DeepseekV3NaiveMoe` branch below never matches the generated class.
            # Design §7 item 3: residual-stream down_proj uses std / sqrt(2 * L).
            init.normal_(
                module.down_proj,
                mean=0.0,
                std=self.config.initializer_range / math.sqrt(2 * self.config.num_hidden_layers),
            )
        # Residual-stream projections (o_proj / down_proj) are re-initialized
        # with std / sqrt(2 * L) for pre-norm stability at initialization
        # (design §7 item 3, L = 28 -> scale ~= 0.00267).
        if getattr(module, "_is_residual_proj", False):
            scaled = self.config.initializer_range / math.sqrt(2 * self.config.num_hidden_layers)
            init.normal_(module.weight, mean=0.0, std=scaled)
        elif isinstance(module, CamelliaMoE):
            pass  # handled below through the NaiveMoe branch
        elif isinstance(module, DeepseekV3NaiveMoe):
            init.normal_(module.gate_up_proj, mean=0.0, std=self.config.initializer_range)
            init.normal_(
                module.down_proj,
                mean=0.0,
                std=self.config.initializer_range / math.sqrt(2 * self.config.num_hidden_layers),
            )
        elif isinstance(module, CamelliaKDAAttention):
            init.normal_(module.dt_bias, mean=0.0, std=0.1)


class CamelliaRotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: CamelliaConfig, device=None):
        super().__init__()
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config

        self.rope_type = self.config.rope_parameters["rope_type"]
        rope_init_fn: Callable = self.compute_default_rope_parameters
        if self.rope_type != "default":
            rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]
        inv_freq, self.attention_scaling = rope_init_fn(self.config, device)

        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.register_buffer("original_inv_freq", inv_freq.clone(), persistent=False)

    @staticmethod
    def compute_default_rope_parameters(
        config: CamelliaConfig | None = None,
        device: Optional["torch.device"] = None,
        seq_len: int | None = None,
    ) -> tuple["torch.Tensor", float]:
        """
        Computes the inverse frequencies according to the original RoPE implementation
        Args:
            config ([`~transformers.PreTrainedConfig`]):
                The model configuration.
            device (`torch.device`):
                The device to use for initialization of the inverse frequencies.
            seq_len (`int`, *optional*):
                The current sequence length. Unused for this type of RoPE.
        Returns:
            Tuple of (`torch.Tensor`, `float`), containing the inverse frequencies for the RoPE embeddings and the
            post-processing scaling factor applied to the computed cos/sin (unused in this type of RoPE).
        """
        base = config.rope_parameters["rope_theta"]
        dim = getattr(config, "head_dim", None) or config.hidden_size // config.num_attention_heads

        attention_factor = 1.0  # Unused in this type of RoPE

        # Compute the inverse frequencies
        inv_freq = 1.0 / (
            base ** (torch.arange(0, dim, 2, dtype=torch.int64).to(device=device, dtype=torch.float) / dim)
        )
        return inv_freq, attention_factor

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with maybe_autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


def compute_cu_seqlens(input_ids: torch.Tensor, eos_token_id: int) -> torch.Tensor:
    """Build packed `cu_seqlens` from intra-document EOS markers.

    Args:
        input_ids: `[B, T]` token ids. Each document in a packed frame ends with
            `eos_token_id`.
        eos_token_id: The boundary token id.

    Returns:
        `LongTensor` of shape `[1 + num_docs]` covering the flattened `B*T`
        stream, or `None` when no boundary is found.
    """
    if input_ids.shape[0] * input_ids.shape[1] == 0:
        return None
    B, T = input_ids.shape
    S = B * T
    positions = torch.nonzero(input_ids == eos_token_id, as_tuple=False)
    if positions.numel() == 0:
        return None
    flat = positions[:, 0] * T + positions[:, 1] + 1
    flat = torch.unique(flat, sorted=True)
    # drop zero-length segments (consecutive boundaries)
    keep = flat[1:] > flat[:-1]
    flat = torch.cat([flat[:1], flat[1:][keep]])
    # A frame may end mid-document (packing cuts at arbitrary token offsets);
    # the trailing partial document becomes its own segment so `cu_seqlens`
    # always covers the full stream (contract of the fla varlen kernels).
    if int(flat[-1]) < S:
        flat = torch.cat([flat, torch.tensor([S], dtype=torch.long, device=flat.device)])
    return torch.cat([torch.zeros(1, dtype=torch.long, device=input_ids.device), flat.to(torch.long)])


@auto_docstring
class CamelliaModel(CamelliaPreTrainedModel):
    def __init__(self, config: CamelliaConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size
        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [CamelliaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = DeepseekV3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = CamelliaRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # Per-MoE-layer routed token counters + per-expert output RMS stats
        self.moe_layers = [layer for layer in self.layers if isinstance(layer.mlp, CamelliaMoE)]
        n_experts = config.n_routed_experts
        self.register_buffer(
            "moe_load_stats",
            torch.zeros(len(self.moe_layers), n_experts, dtype=torch.float32),
            persistent=False,
        )
        self.register_buffer(
            "moe_out_norm_stats",
            torch.zeros(len(self.moe_layers), n_experts, dtype=torch.float32),
            persistent=False,
        )
        self.register_buffer(
            "moe_out_hit_stats",
            torch.zeros(len(self.moe_layers), n_experts, dtype=torch.float32),
            persistent=False,
        )
        for i, layer in enumerate(self.moe_layers):
            layer.mlp._load_stats = self.moe_load_stats[i]
            layer.mlp.experts._out_norm_stats = self.moe_out_norm_stats[i]
            layer.mlp.experts._out_hit_stats = self.moe_out_hit_stats[i]

        # Initialize weights and apply final processing
        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values=None,
        inputs_embeds: torch.FloatTensor | None = None,
        use_cache: bool | None = None,
        **kwargs,
    ) -> BaseModelOutputWithPast:
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        # Packed intra-document boundaries (design §7 実装前確定事項 1):
        # KDA resets its recurrent state and MLA masks across documents.
        cu_seqlens = None
        if input_ids is not None and self.config.eos_token_id is not None:
            cu_seqlens = compute_cu_seqlens(input_ids, self.config.eos_token_id)

        hidden_states = inputs_embeds
        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            hidden_states = decoder_layer(hidden_states, cu_seqlens=cu_seqlens, **kwargs)

        hidden_states = self.norm(hidden_states)
        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values,
        )

    def reset_moe_load_stats(self) -> None:
        self.moe_load_stats.zero_()
        self.moe_out_norm_stats.zero_()
        self.moe_out_hit_stats.zero_()


def _adjust_cu_seqlens(cu_seqlens: torch.Tensor | None, B: int, T: int) -> torch.Tensor | None:
    """Map packed `cu_seqlens` from the B*T stream to the MTP B*(T-1) stream.

    The MTP stream drops each batch row's last position, so a boundary at
    flat position p in batch b = p // T moves to p - b (the row end of the
    full stream, p = B*T, maps to B*(T-1)). Zero-length segments (a
    1-token document ending exactly at a row end) are dropped.
    """
    if cu_seqlens is None:
        return None
    rest = cu_seqlens[1:]
    shifted = rest - rest // T
    cu = torch.cat([cu_seqlens[:1], shifted])
    keep = cu[1:] > cu[:-1]
    return torch.cat([cu[:1], cu[1:][keep]])


@auto_docstring
class CamelliaForCausalLM(CamelliaPreTrainedModel, GenerationMixin):
    """NTP + MTP (D=1) training objective.

    `loss = L_ntp + mtp_lambda * L_mtp` where `mtp_lambda` is a mutable
    attribute (set by the training loop from the config schedule).
    """

    _tied_weights_keys = {"lm_head.weight": "model.embed_tokens.weight"}
    _tp_plan = {"lm_head": "colwise_gather_output"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config: CamelliaConfig):
        super().__init__(config)
        self.model = CamelliaModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)
        if config.num_nextn_predict_layers > 0:
            self.mtp = CamelliaMTPModule(config)
        else:
            self.mtp = None
        self.mtp_lambda: float = config.mtp_lambda_high

        # Initialize weights and apply final processing
        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values=None,
        inputs_embeds: torch.FloatTensor | None = None,
        labels: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        logits_to_keep: int | torch.Tensor = 0,
        **kwargs,
    ) -> CausalLMOutputWithPast:
        r"""
        Example:

        ```python
        >>> from transformers import AutoTokenizer, CamelliaForCausalLM

        >>> model = CamelliaForCausalLM.from_pretrained("meta-camellia/Camellia-2-7b-hf")
        >>> tokenizer = AutoTokenizer.from_pretrained("meta-camellia/Camellia-2-7b-hf")

        >>> prompt = "Hey, are you conscious? Can you talk to me?"
        >>> inputs = tokenizer(prompt, return_tensors="pt")

        >>> # Generate
        >>> generate_ids = model.generate(inputs.input_ids, max_length=30)
        >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        "Hey, are you conscious? Can you talk to me?\nI'm not conscious, but I can talk to you."
        ```"""
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        mtp_loss = None
        if labels is not None and self.mtp is not None and input_ids is not None:
            B, T = input_ids.shape[0], input_ids.shape[1]
            cu_seqlens = (
                compute_cu_seqlens(input_ids, self.config.eos_token_id)
                if self.config.eos_token_id is not None
                else None
            )
            next_embeds = self.model.embed_tokens(torch.roll(input_ids, shifts=-1, dims=1))
            combined = torch.cat([next_embeds[:, :-1], hidden_states[:, :-1]], dim=-1)  # [B, T-1, 2D]
            mtp_cu = _adjust_cu_seqlens(cu_seqlens, B, T)
            mtp_hidden = self.mtp(combined, cu_seqlens=mtp_cu)
            mtp_logits = self.lm_head(self.model.norm(mtp_hidden))
            # labels = input_ids (unshifted, PackedDataset convention).
            # NTP: logits[t] predicts x_{t+1} -> pair logits[:T-1] with labels[1:].
            # MTP: mtp_logits[t] predicts x_{t+2} -> pair mtp_logits[:T-2] with labels[2:]
            # (the last MTP position has no in-sequence target x_T).
            mtp_logits = mtp_logits[:, :-1]
            shift_logits = mtp_logits.contiguous().view(-1, self.config.vocab_size)
            shift_labels = labels[:, 2:].contiguous().view(-1)
            mtp_loss = F.cross_entropy(shift_logits, shift_labels, ignore_index=-100)
            ntp_logits = logits[:, :-1].contiguous().view(-1, self.config.vocab_size)
            ntp_labels = labels[:, 1:].contiguous().view(-1)
            loss = F.cross_entropy(ntp_logits, ntp_labels, ignore_index=-100) + self.mtp_lambda * mtp_loss
        elif labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
        )


__all__ = ["CamelliaForCausalLM", "CamelliaModel", "CamelliaPreTrainedModel"]
